name: My CICD pipeline in GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize Repo
        run: |
          echo "This is DevOps"
          uname -a

      - name: Check Docker installation
        run: |
          docker --version
          docker images

      - name: Run Docker Container
        run: |
          docker run hello-world
